import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  {
    id: 0.25,
    name: "Client",
    href: "https://img4.nbstatic.in/tr:w-500/5bb2184952faff000c279344.png",
    image: "https://img4.nbstatic.in/tr:w-500/5bb2184952faff000c279344.png",
    imageLight: "/images/brand/brand-dark-01.svg",
  },
  {
    id: 0.3,
    name: "Mahaveer Cotton",
    href: "https://www.gennextit.com/assets/Frontend/logo/Mahaveer-cotton.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/Mahaveer-cotton.png",
    imageLight: "/images/brand/brand-dark-02.svg",
  },
  {
    id: 0.4,
    name: "Sarvodaya",
    href: "https://www.gennextit.com/assets/Frontend/logo/Sarvodaya.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/Sarvodaya.png",
    imageLight: "/images/brand/brand-dark-03.svg",
  },
  {
    id: 0.5,
    name: "IndianMart",
    href: "https://www.gennextit.com/assets/Frontend/logo/indianmart.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/indianmart.png",
    imageLight: "/images/brand/brand-dark-04.svg",
  },
  {
    id: 0.6,
    name: "Grant Thornton",
    href: "https://www.gennextit.com/assets/Frontend/logo/grantthortaon.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/grantthortaon.png",
    imageLight: "/images/brand/brand-dark-05.svg",
  },
  {
    id: 0.7,
    name: "Zomato",
    href: "https://www.gennextit.com/assets/Frontend/logo/zomato-logo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/zomato-logo.png",
    imageLight: "/images/brand/brand-dark-06.svg",
  },
  {
    id: 0.8,
    name: "BNCHY",
    href: "https://www.gennextit.com/assets/Frontend/logo/BNCHY-logo.webp",
    image: "https://www.gennextit.com/assets/Frontend/logo/BNCHY-logo.webp",
    imageLight: "/images/brand/brand-dark-07.svg",
  },
  {
    id: 0.9,
    name: "OYO",
    href: "https://www.gennextit.com/assets/Frontend/logo/OYOlogo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/OYOlogo.png",
    imageLight: "/images/brand/brand-dark-08.svg",
  },
  {
    id: 1.0,
    name: "NIIT",
    href: "https://www.gennextit.com/assets/Frontend/logo/NIIT-logo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/NIIT-logo.png",
    imageLight: "/images/brand/brand-dark-09.svg",
  },
  {
    id: 1.1,
    name: "Monet",
    href: "https://www.gennextit.com/assets/Frontend/logo/monetLogo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/monetLogo.png",
    imageLight: "/images/brand/brand-dark-10.svg",
  },
  {
    id: 1.2,
    name: "CSC",
    href: "https://www.gennextit.com/assets/Frontend/logo/csc-logo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/csc-logo.png",
    imageLight: "/images/brand/brand-dark-11.svg",
  },
  {
    id: 1.3,
    name: "NMC Genetics",
    href: "https://www.gennextit.com/assets/Frontend/logo/nmcgeneticslogo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/nmcgeneticslogo.png",
    imageLight: "/images/brand/brand-dark-12.svg",
  },
  {
    id: 1.4,
    name: "UPSMA",
    href: "https://www.gennextit.com/assets/Frontend/logo/upsma-logo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/upsma-logo.png",
    imageLight: "/images/brand/brand-dark-13.svg",
  },
  {
    id: 1.5,
    name: "Nulearn",
    href: "https://www.gennextit.com/assets/Frontend/logo/Nulearn-logo.svg",
    image: "https://www.gennextit.com/assets/Frontend/logo/Nulearn-logo.svg",
    imageLight: "/images/brand/brand-dark-14.svg",
  },
  {
    id: 1.6,
    name: "RBS",
    href: "https://www.gennextit.com/assets/Frontend/logo/r-b-s-logo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/r-b-s-logo.png",
    imageLight: "/images/brand/brand-dark-15.svg",
  },
  {
    id: 1.7,
    name: "Navisite",
    href: "https://www.gennextit.com/assets/Frontend/logo/Navisite_logo_white.png",
    image:
      "https://www.gennextit.com/assets/Frontend/logo/Navisite_logo_white.png",
    imageLight: "/images/brand/brand-dark-16.svg",
  },
  {
    id: 1.8,
    name: "LazerKen",
    href: "https://www.gennextit.com/assets/Frontend/logo/lazerKen.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/lazerKen.png",
    imageLight: "/images/brand/brand-dark-17.svg",
  },
  {
    id: 1.9,
    name: "BDO",
    href: "https://www.gennextit.com/assets/Frontend/logo/BDO_logo.png",
    image: "https://www.gennextit.com/assets/Frontend/logo/BDO_logo.png",
    imageLight: "/images/brand/brand-dark-18.svg",
  },
];

export default brandData;
